### ISSUE TITLE
Change Time Zone

### ISSUE THREAD

**Issue by total20303** [JaredScar/Badssentials#10]
If our server is set on Berlin time but we are in EST is there a way to change the displayed time to the correct EST time?

**Comment by NickReagan** [comment]
I will look into this for ya.

**Comment by JaredScar** [comment]
Thinking about it now, we probably should change `EST` placeholder to something like `TIME_LOCAL` or something since it's really just reading the system clock I believe

**Comment by NickReagan** [comment]
> 

I am going to be doing some testing with it, maybe add it as a config variable with it defaulted to local but if they need to they can change it.

**Comment by total20303** [comment]
Thanks so much guys for you help with this......I appreciate you looking into it.

**Comment by Willow-6855** [comment]
> Thinking about it now, we probably should change `EST` placeholder to something like `TIME_LOCAL` or something since it's really just reading the system clock I believe

It uses CST time not EST time

**Comment by JaredScar** [comment]
This has been changed to `{OS_TIME}` since that better reflects how it currently works. If someone wants to feel free to make a PR to support any timezone, that'd be cool 😄
