### ISSUE TITLE
Display in game time instead of local time?

### ISSUE THREAD

**Issue by ResqDiver1317** [JaredScar/Badssentials#14]
I was wondering if it would be possible to show the in game time instead of the local/system time?

**Comment by NickReagan** [comment]
Made a PR for it, as of the moment it can only display the time in 24hr format.

**Comment by ResqDiver1317** [comment]
I personally am good with 24hr time. Makes it easier for reportsSent from my iPhoneOn Jan 15, 2024, at 08:41, Nick Reagan ***@***.***> wrote:﻿
Made a PR for it, as of the moment it can only display the time in 24hr format.
