### ISSUE TITLE
If I remove badssentials my server gets stuck in the loading screen

### ISSUE THREAD

**Issue by GooseMan0001** [JaredScar/Badssentials#3]
I've disabled every single resource in my server that isn't default or badssentials, and I still get stuck in the loading screen, if I start badssentials, or add it back after removing it from my server, it magically loads into the gam.e like normal.
What the actual fuck is happening? I would trust Badger enough to say that there is no malware, but I am certainly not doing anything wrong on my end

**Comment by JaredScar** [comment]
You're doing something wrong...
